config/routes.rb
Rails.application.routes.draw do
  
  root "pages#index"
  devise_for :users
  resources :users
  devise_for :locations
  resources :locations
  devise_for :groups
  resources :groups

  # get '/locations', to: 'location#index'
  # get '/locations/:id', to: 'location#show'

  # get '/users', to: 'user#index'
  # post '/users/:id', to: 'user#show'

  # post '/groups/new', to: 'group#new', as: 'new_group'
  # post '/groups/', to: 'group#create'
  # get '/groups', to: 'group#index'
  # get '/groups/:id', to: 'group#show'

  patch '/join', to: 'users#join', as: :join
  post '/groups/new', to: 'groups#new'

end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :string(255)
#  time        :string(255)
#  location    :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  location_id :integer
#

class Group < ActiveRecord::Base
	has_many :manifests
	has_many :users, through: :manifests
end

app/models/location.rb
# == Schema Information
#
# Table name: locations
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#  address     :string(255)
#

class Location < ActiveRecord::Base
	has_many :groups
end

app/models/manifest.rb
# == Schema Information
#
# Table name: manifests
#
#  id         :integer          not null, primary key
#  created_at :datetime
#  updated_at :datetime
#  user_id    :integer
#  group_id   :integer
#

class Manifest < ActiveRecord::Base
	belongs_to :group
	belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  created_at             :datetime
#  updated_at             :datetime
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  username               :string(255)
#  name                   :string(255)
#  year                   :integer
#  major                  :string(255)
#  phone                  :integer
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :authentication_keys => [:name, :username, :email, :year, :major]
  has_many :manifests
  has_many :groups, through: :manifests
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/group_controller.rb
class GroupController < ApplicationController

	def create
    	@group = Group.create(group_params)
    	if @group.save
	    	redirect_to ("/groups/") #Redirect to location of the group created
 		else 
 			flash[:error] = @group.errors.full_messages.to_sentence
 			redirect_to new_group_path
 		end
	end

	def group_params
    	params.require(:group).permit(:name, :location)
  	end

    def new
		 @group = Group.new
	end

	def destroy
		@group.destroy
		flash[:notice] = "This group has been deleted."
	end

	def index
		@groups = Group.all
	end

	def show
		 @groups = Group.find(params[:id])
	end

	def sortByTime
		 @sorted_groups = Group.sort_by {|g| Chronic.parse(g.time)}
	end
	def join
		@group = Group.find(params[:id])
		user = current_user 
		group.users <<  user # add user to group
		@group.save
		redirect_to group_path
	end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	def create
    	@group = Group.create(group_params)
    	@locName = group_params[:location]
    	@actualLoc = Location.find_by name: @locName
    	@group.location_id = @actualLoc.id
    	if @group.save
	    	redirect_to ("/groups/") #Redirect to location of the group created
 		else 
 			flash[:error] = @group.errors.full_messages.to_sentence
 			redirect_to new_group_path
 		end
	end

	def group_params
    	params.require(:group).permit(:name, :description, :location, :time)
  	end

    def new
		 @group = Group.new
	end

	def destroy
		@group.destroy
		flash[:notice] = "This group has been deleted."
	end

	def index
		@group = Group.all
	end

	def show
		 @group = Group.find(params[:id])
	end

	def sortByTime
		 @sorted_groups = Group.all.sort_by {|g| Chronic.parse(g.time)}
	end

end

app/controllers/location_controller.rb
class LocationController < ApplicationController
	before_action :authenticate_user!
	def index
		@locations = Location.all
	end

	def show
		 @location = Location.find(params[:id])
	end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
	before_action :authenticate_user!
	def index
		@locations = Location.all
	end

	def show
		 @location = Location.find(params[:id])
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	def index
    	@users = User.all
  	end

  	def show
   	 	@user = User.find(params[:id])
  	end

    def join
      @group = Group.find(params[:id])
      @user = current_user
      if @user.groups.include?(@group)
        flash[:notice] = "You're already in " + @group.name + "!"
        redirect_to :back
      else
        @user.groups << @group 
        @group.users << @user # add user to group
        if @user.save
          flash[:notice] = "You've successfully joined " + @group.name + "!"
          redirect_to :back
        end
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/group/index.html.erb
<% Group.all.each do |group| %>
<% @url = "/groups/" + group.id.to_s %>
	<a href = <%= @url %> > <h2><%= group.name %></h2> </a>
<% end %>

app/views/group/new.html.erb
<h2> Create A Group </h2>
<%= simple_form_for Group.new do |f| %>
  Name <%= f.text_field :name %>
  Description <%= f.text_field :description %>
  Location <%= f.text_field :location %>
  Time <%= f.text_field :time %>

  <%= f.submit "Create" %>
<% end %>

app/views/groups/index.html.erb
<br>
<%= button_to "+ Create a group", new_group_path() %> 
<!-- ERROR: no route matches post -->

<% Group.all.each do |group| %>
<% @url = "/groups/" + group.id.to_s %>
	<a href = <%= @url %> > <h2><%= group.name %></h2> </a>
<% end %>

app/views/groups/new.html.erb
<h2> Create A Group </h2>
<%= simple_form_for @group do |f| %>
  Name <%= f.input :name %>
  Description <%= f.input :description %>
  Location <%= f.select :location, ["Cafe3", "Clark Kerr", "Crossroads", "Foothill"]%>
  Time <%= f.input :time %>

  <%= f.submit "Create" %>
<% end %>

app/views/groups/show.html.erb
<h1><%= @group.name %></h1>
			    <%= @group.description %> <br>
			    <%= @group.time %> <br>
			    <%= @group.location %> <br>
<%= button_to "Join this group", join_path(id: @group.id), :class => "button medium", :method => :patch %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'dinr', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
<li><%= link_to 'Profile', user_path(current_user) %></li>
  <li><%= link_to 'Log Out', destroy_user_session_path, :method=>'delete' %></li>

<% else %>
  <li><%= link_to 'Log In', new_user_session_path %></li>
  <li><%= link_to 'Join dinr', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
      <%= favicon_link_tag 'favicon.ico' %>
    <link rel="icon" type="image/png" href="favicon-32x32.png" sizes="32x32" />
    <link rel="icon" type="image/png" href="favicon-16x16.png" sizes="16x16" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "dinr" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "bettr than tinder" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/locations/index.html.erb
<br>
<div class="row">
  <div class="col-sm-6">
 
    <!-- normal -->
    <% Location.all.each do |location| %>
    <% @url = "/locations/" + location.id.to_s %>
    <div class="ih-item circle effect1"><a href = <%= @url %> >
        <div class="spinner"></div>
        <div class="img"><%= image_tag("cafe3.jpg", :alt => "cafe") %></div>
        <div class="info">
          <div class="info-back">
            <h3><%= location.name %></h3>
            <p><%= location.address %></p>
          </div>
        </div></a></div>
      <br>
    <% end %>
    <!-- end normal -->
 
  </div>
</div>

app/views/locations/show.html.erb
<h1><%= @location.name %></h1> 
<br>
<table class="groups">
	<tr>
		<th>Group</th>
		<th>Description</th>
		<th>Time</th>
	</tr>
	<% @sorted_groups = Group.all.sort_by {|g| Chronic.parse(g.time)} %>
	  <% @sorted_groups.each do |g| %>
		  <% if g.location == @location.name %>
			  <tr>
			    <td><%= g.name %></td>
			    <td><%= g.description %></td> 
			    <td><%= g.time %></td>
			  </tr>
		  <% end %>
	  <% end %>
</table>

app/views/pages/index.html.erb
<center>
<a href="#"><%= image_tag("dinr.png", :alt => "dinr logo", :style => "width:20%") %></a>

<h4><%= link_to 'Locations', locations_path %></h4>
<h4><%= link_to 'Groups', groups_path %></h4>


<footer>Final Project @ UC Berkeley's Rails Decal <br>
	Created by Jenny Li, Saloni Shah, Dipsikha Halder, Jeffrey Lin</footer>
</center>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= user.name %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3><%= @user.name %></h3>  <%= link_to 'Edit Profile', edit_user_registration_path %>
<p>Email: <%= @user.email if @user.email %></p>
<p>Year: <%= @user.year if @user.year %></p>
<p>Major: <%= @user.major if @user.major %></p>
<p>Groups: 
	<% @user.groups.each do |g| %>
		<%= g.name %> <br>
	<% end %>
</p>
<br>